import { Octokit } from '@octokit/rest';
import { QuizPayload } from '@/types/archicheck';

/**
 * Service responsible for generating user-friendly markdown for PR discussions
 * and interacting with GitHub comment endpoints.
 */
export class GitHubCommentsService {
  /**
   * Translates a QuizPayload object into structured Markdown.
   * 
   * @param quiz The QuizPayload generated by the LLM.
   * @returns A markdown string representing the interactive quiz.
   */
  generateQuizMarkdown(quiz: QuizPayload): string {
    const header = `## ⚠️ High Algorithmic Complexity Detected\n\nTo preserve systemic intuition and prevent comprehension debt, automated merging is paused. Please answer the architectural questions below directly by replying to this comment.\n\n`;
    
    const body = quiz.questions
      .map((q, idx) => {
        return `### Question ${idx + 1}: ${q.question}\n- **Target File**: \`${q.targetFile}\`\n- **Target Code**:\n\`\`\`typescript\n${q.codeSnippet}\n\`\`\`\n\n`;
      })
      .join('');

    const footer = `\n---\n*Reply to this comment in the format:*\n\`\`\`\n1. [Your answer for Q1]\n2. [Your answer for Q2 if applicable]\n\`\`\``;

    return `${header}${body}${footer}`;
  }

  /**
   * Posts the architectural quiz to the pull request comment thread.
   * 
   * @param client Authenticated Octokit client.
   * @param owner Repository owner login.
   * @param repo Repository name.
   * @param issueNumber The pull request (issue) number.
   * @param quiz Markdown-formatted quiz string.
   * @returns The ID of the created comment.
   */
  async postQuizComment(
    client: Octokit,
    owner: string,
    repo: string,
    issueNumber: number,
    quiz: string,
  ): Promise<number> {
    const response = await client.issues.createComment({
      owner,
      repo,
      issue_number: issueNumber,
      body: quiz,
    });
    return response.data.id;
  }

  /**
   * Updates an existing comment with a validation result.
   * 
   * @param client Authenticated Octokit client.
   * @param owner Repository owner login.
   * @param repo Repository name.
   * @param commentId The comment ID to update.
   * @param content The updated markdown text.
   */
  async updateComment(
    client: Octokit,
    owner: string,
    repo: string,
    commentId: number,
    content: string,
  ): Promise<void> {
    await client.issues.updateComment({
      owner,
      repo,
      comment_id: commentId,
      body: content,
    });
  }
}

export const gitHubCommentsService = new GitHubCommentsService();
